rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::DeviceExample -> cboard_example
      - rmcs_core::example::RemoteControllerExample -> remote_control_message
      - rmcs_core::controller::pid::PidController -> gm6020_velicity_controller


cboard_example:
  ros__parameters:
    usb_pid: -1

gm6020_velicity_controller:
  ros__parameters:
    setpoint: /example/gm6020/control_velocity
    measurement: /example/gm6020/velocity
    control: /example/gm6020/control_torque
    kp: 10.0
    ki: 0.0
    kd: 0.0