name: Build and Push RMCS Images

on:
  workflow_dispatch:
  push:
    paths:
    - 'Dockerfile'
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push rmcs-develop:latest
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        target: rmcs-develop
        tags: qzhhhi/rmcs-develop:latest

    - name: Build and push rmcs-runtime:latest
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        target: rmcs-runtime
        tags: qzhhhi/rmcs-runtime:latest
